src/app/game-state/character.ts

statLifespan is currently calculated from attribute value on reincarnation rather than what looks to be the intended attribute aptitude on reincarnation.

Fix attributes aptitude contribution to statLifespan.

---

src/app/game-state/character.ts

This move allows other interesting means of increasing the base lifespan that don't rely on 15k deaths, and allows for different limits to be easily set later if desired.

Moved baselifespan increase to Method

---

src/app/game-state/home.service.ts
src/app/options-modal/options-modal.component.html
src/app/options-modal/options-modal.component.ts

Adds a checkbox to enable the static auto-buy reserve, and an input element to input the amount to be reserved. If the box is unchecked, the reserve amount is ignored and 10 * daily expenses is used. If checked, it uses the input instead of the base reserve amount.

Auto-buy reserve options

---

src/app/activity-panel/activity-panel.component.html
src/app/activity-panel/activity-panel.component.ts

This allows the user to Shift Click on activities to add them with 10 days to start with, instead of just the base 1.

Shift Click when adding activities to start at 10

---

src/app/app.component.less
src/app/time-panel/time-panel.component.html
src/app/time-panel/time-panel.component.less

Ensures that the header and footer on the schedule tab are always visible.
Additionally, fixes the height of both the schedule and attribute panel to both be half the height of the remaining space.

Always keep header and footer visible on schedule

---

src/app/ascension-store-modal/ascension-store-modal.component.html
src/app/game-state/achievement.service.ts
src/app/game-state/character.service.ts
src/app/game-state/character.ts
src/app/game-state/store.service.ts

[Original bug by Cho Quan](https://discord.com/channels/996414713766363146/996488799938936922/998227561584808007)
Possible Solutions:
1. Change wording of bloodline rank 4 to also add lifespan
2. **Enable purchasing of Bloodline Rank 5 & change requirement to match wording**
3. other
I've gone with option two, but am very open to being overridden.
I am not a huge fan of making balance changes, but I feel this game is desperately in need of some. This one teeters on a bug fix.
I did not look at Soul Core/Meridians, they may have a similar 'bug'.

fix: bloodline rank five and lifespan

---

src/app/game-state/character.service.ts
src/app/game-state/main-loop.service.ts

Stop death consumning ticks of the next life by:
- During the iteration of the ticks in main loop service if the game is paused during a tick, the nexts are not executed and saved in the banked ticks instead.
- During the reincarnation in character service moving the actual reincarnation of the player to the next tick for stopping the next observables called during this tick of executing.

#23 Pause on death should stop without starting the next life

---

src/app/ascension-store-modal/ascension-store-modal.component.html
src/app/game-state/home.service.ts
src/app/home-panel/home-panel.component.html

Empowerment pill clarification can be split out if this tooltip moving isn't appreciated.
House tooltips needed to be updated, since "a bit of health" is inaccurate when it recovers 80, and it doesn't mention mana recovery at all. While we're at it, might as well have the upgrade tooltip say what the advantage of an upgraded house will be. 
Possible changes to consider: 
- changing from "next house's values" to "difference between this house and next house". 
- moving all of this back to home-panel's html and figuring out how to put if statements in html. 
- creating and using variables in the descriptions to make possible/eventual globalization and localization marginally easier.
- if variables are created, use them inside of consequence function.

Fix: Improving home information

---

src/app/time-panel/time-panel.component.less
src/styles.less

Because the contrast between the 'active' background color and regular
background color is so low, telling which button in the time panel is
active is not trivial (especially in the dark mode).
Swapping the foreground and background colors of the active button makes
it easy to tell it apart from the others at a glance, while preserving
the color theme.

Improve contrast of active time panel button

---

src/app/game-state/achievement.service.ts
src/app/game-state/activity.service.ts
src/app/game-state/character.service.ts
src/app/game-state/character.ts

Balance update:
- Aptitude multiplier will grow very slow once more than 100,000, thus fixing the problem of too many lifespan and too many stats
Reducing the cost to train followers to become 500m
and reducing the cost of bloodline 5 to become 9.375T
in order to make sure the game not become too hard after the nerf.

Aptitude multiplier balancing

---

src/app/game-state/character.ts
src/app/game-state/store.service.ts

Anything greater than 1000++ lifespan is actually very good for pre-impossible stage.
Having lifespan too long will make the game boring.
So instead of increasing spirituality lifespan, I set it so that you only get that increased lifespan when you reach impossible, that is the time you really need 10k++ lifespan

Balancing adjustment

---

src/app/activity-panel/activity-panel.component.ts
src/app/attributes-panel/attributes-panel.component.ts
src/app/farm-panel/farm-panel.component.ts
src/app/home-panel/home-panel.component.ts
src/app/inventory-panel/inventory-panel.component.ts
src/app/time-panel/time-panel.component.ts

Very simple adjustment here. I use a macbook to play the game, but ctrl-click gets reserved at the OS level to perform a right click action. (Or vice versa depending on perspective)
This PR just adds an OR event.metaKey to the places where event.ctrlKey is used. I didn't make any interface changes, because I didn't know how that might want to be handled up stream, but at least the functionality is accessible now.

MACOS: Use ctrl OR cmd click due to OS reservation

---

src/app/game-state/item-repo.service.ts
src/app/game-state/main-loop.service.ts
src/app/statistics-panel/statistics-panel.component.ts

- Updates the way each frame tries using ticks to avoid stalling past base FPS.
- Updates bankedTicks use and gain, including higher rates with higher TPS and using one bankedTick per actual use rather than estimated use.
- Included gaining partial bankedTicks for going slower than bankedTicks gain.

Fix: FPS drop for high ticks, bankedTicks gain/use

---

src/app/game-state/main-loop.service.ts

- Added a check for bankedTicks overuse, which also requires the removal of the now defunct lag prevention (since the loop exits after a certain amount of time) to function correctly.

Update for inactive and removing limiters

---

src/app/game-state/inventory.service.ts
src/app/inventory-panel/inventory-panel.component.html

Sort priority is type, value, then quantity, then name. Kinda want to subgroup the materials and toss gems to the bottom but there's no real way to easily do so based on item properties.

Added inventory sort button.

---

src/app/options-modal/options-modal.component.ts

From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt:
"For example, although 1e3 technically encodes an integer (and will be correctly parsed to the integer 1000 by [parseFloat()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat)), parseInt("1e3", 10) returns 1, because e is not a valid numeral in base 10. Because . is not a numeral either, the return value will always be an integer."

Made 1e6 a valid input

---

src/app/game-state/achievement.service.ts

Formed by popular demand, for exactly the number of pills required to display 100.

Add: "Dope" Achievement.

---

src/app/game-state/main-loop.service.ts

Use a relative path because the experimental version is not at the root.

Fix music URL for experimental branch

---

src/app/time-panel/time-panel.component.html

when space is held and the bankedCycles are used up the game switches between pause and the last speed setting
creating a situation where the bankedCycles element repeatedly gets drawn and not
the change sets the bankedCycles check to >1 from my testing (rather early save) thats enough to prevent the flicker
before:
https://github.com/immortalityidle/immortalityidle.github.io/assets/115591472/72652b1c-f284-46b5-94c7-f470e1664be7
after:
https://github.com/immortalityidle/immortalityidle.github.io/assets/115591472/d11ef153-8f1a-49cc-b4f0-d9966efd0332

remove bankedCycle flicker when space is held

---

src/app/game-state/item-repo.service.ts

- Capitalize "Crown" in all crown-related descriptions
- Standardize description format to "A crown proving your mastery over the Hell of [Name]"
- Add specific crown names in descriptions for clarity
- Maintain consistent formatting across all crown items

Standardize crown descriptions in item-repo.service.ts
