src/styles.less

Makes darkmode easier on the eyes

Reduce contrast in darkmode

---

src/app/equipment-panel/equipment-panel.component.html
src/app/inventory-panel/inventory-panel.component.html
src/app/inventory-panel/inventory-panel.component.less
src/app/inventory-panel/inventory-panel.component.ts

- restyled amounts in inventory slots
- attempted and failed to find bug in scrollbar

updated issue with amounts

---

src/app/game-state/activity.service.ts

Reduction to 50 million charisma for follower recruitment at about 150-170 years old

Follower requirement reduction

---

src/app/ascension-store-modal/ascension-store-modal.component.html
src/app/game-state/character.ts

People have already hit cap. Too late to take it back and too late to balance but this exists.

Empowerment Balance try 2

---

src/app/game-state/character.ts
src/app/game-state/inventory.service.ts

Reduced max to 100 and removed the overage check since the formula naturally converges at 100.

Empowerment rebalance 3

---

src/app/game-state/activity.service.ts
src/app/game-state/followers.service.ts
src/app/game-state/home.service.ts
src/app/game-state/main-loop.service.ts

I have replaced some of the for loops with calls that use a parameter like for addItem and upgradeTick.
In home.service i have changed upgradeTick to take a parameter so that it only has be run once for the scout.
In places where a value was incremented by 1 in a for loop i have replaced them with a direct value.
In main-loop i have replaced a for loop based on a Math.floor with the result or 100 using Math.min.

A little less for loops

---

src/app/game-state/inventory.service.ts

Because of the meridian being under 5

Fixes gemology negative power

---

src/app/game-state/character.ts
src/app/options-modal/options-modal.component.ts

If the numerical options fields are left blank it causes issues. Simple fix.

Some options fixes while I balance

---

src/app/game-state/impossibleTask.service.ts

Code looks good, but still working on testing.

Added fix to reincarnation for impossible tasks

---

src/app/game-state/activity.service.ts

This greatly reduces the impact of luck affecting player's stat

All attribute gain is now more consistent

---

package-lock.json
src/app/app.module.ts
src/app/log-filter-panel/log-filter-panel.component.html
src/app/log-filter-panel/log-filter-panel.component.spec.ts
src/app/log-filter-panel/log-filter-panel.component.ts
src/app/log-panel/log-panel.component.html
src/app/log-panel/log-panel.component.ts

Moving the log filters to a separate window to allow for more filters in the future

Add panel component for log filters

---

src/app/game-state/activity.service.ts
src/app/game-state/autoBuyer.ts
src/app/game-state/character.service.ts
src/app/game-state/inventory.service.ts

I have implemented quantity for consume.
The result on my local machine is that while running "Gather Armies" 100 years went from taking 24 seconds to taking 8 seconds.

A little less for loops v2

---

src/app/game-state/character.service.ts
src/app/health-panel/health-panel.component.html

When you are immortal negative health is shown as 0 and when the game checks if you are dead then it will be set to 0.
This should solve: https://trello.com/c/GXRtrTgh/46-stop-health-from-going-negative-when-you-are-immortal

Stop health from going negative when you are immortal.

---

src/app/attributes-panel/attributes-panel.component.html
src/app/attributes-panel/attributes-panel.component.less
src/app/follower-management-panel/follower-management-panel.component.html
src/app/follower-management-panel/follower-management-panel.component.ts
src/app/game-state/followers.service.ts
src/app/game-state/game-state.service.ts
src/styles.less

Added the current/max of followers (alignment is a hack please fix) as well as formatting for hitting max, and added button and input in Follower Settings to change all of the follower settings at once to a specific number.

Added follower number & change all + fixes

---

src/app/game-state/achievement.service.ts
src/app/game-state/activity.service.ts
src/app/game-state/character.service.ts
src/app/game-state/character.ts
src/app/game-state/followers.service.ts
src/app/game-state/impossibleTask.service.ts
src/app/game-state/store.service.ts

Re-balance and various fixes

---

src/app/inventory-panel/inventory-panel.component.less

> Inventory Scrollbar moves down automatically #57 
Should now be fixed

Inventory Scrollbar Moved On its own

---

src/app/game-state/achievement.service.ts
src/app/game-state/item-repo.service.ts
src/app/game-state/main-loop.service.ts
src/app/time-panel/time-panel.component.html

this is overall a nerf if you don't use banked time, but it feels way less arbitrary than what it was before. and now that you aren't living to 50k years anyway (probably) having time go way faster isn't as necessary.
(also, this is slabdrill)

change time speed mechanics

---

src/app/follower-management-panel/follower-management-panel.component.html
src/app/follower-management-panel/follower-management-panel.component.ts
src/app/game-state/achievement.service.ts
src/app/game-state/activity.service.ts
src/app/game-state/activity.ts
src/app/game-state/character.service.ts
src/app/game-state/character.ts
src/app/game-state/followers.service.ts
src/app/game-state/item-repo.service.ts
src/app/impossible-task-panel/impossible-task-panel.component.html
src/app/impossible-task-panel/impossible-task-panel.component.ts

Oops, I probably put a bit too much in here while testing... Well, take a peek anyway.
Added autorest and related achievement, added Impossible Tasks autopausing, fixed the follower sorting wobble and added in asc/desc order, and some minor fixes for saving/loading and other such.
Probably so much due to testing and getting frustrated with small things that I fixed to make testing easier, as well as copying over some of the autorest stuff and finding that it included half the autopausing.
Everything is tested, with a minor bug in the autopausing that causes it to pause with negative health if you go step by step trying to kill yourself. Not really something a player would do normally.

Autorest & Impossible AutoPause & Sorting / Ascending & minor fixes

---

src/app/app.component.ts

Now the only thing needed to expand the amount of supported suffixes is to expand the suffix array.

Changed BigNumberPipe to minimize the possibility of error

---

src/app/game-state/activity.service.ts
src/app/game-state/activity.ts
src/app/game-state/character.ts

Also reordered activities so they were a little more relative to each other and lore grouped.

Added Lore Balance Activity

---

src/app/game-state/activity.service.ts
src/app/game-state/inventory.service.ts

Gathering quality fully spreads.

---

src/app/follower-management-panel/follower-management-panel.component.html
src/app/health-panel/health-panel.component.html

https://trello.com/c/kzKTwHj2/111-hide-days-old-after-you-hit-10000-years-old

Hide days old after you hit 10000 years old.

---

src/app/attributes-panel/attributes-panel.component.html
src/app/game-state/activity.service.ts
src/app/game-state/inventory.service.ts

- Piped the equipment descriptions
- Follower level displays
- Spelling

Small suggestions + bugfix

---

src/app/game-state/home.service.ts

Fix for this: https://discord.com/channels/996414713766363146/999627950766956544/1003268344817918012

Buying 10 fields was possible if you had 1 land.

---

src/app/game-state/character.ts

https://discord.com/channels/996414713766363146/999627950766956544/1003144112494620773 Fix

Updates hardcap to limit pill below softcap

---

src/app/game-state/achievement.service.ts

I used the wrong method for updating the nexthome...

Trivial: Bugfix for Imperial homes unlock

---

src/app/game-state/activity.service.ts
src/app/game-state/followers.service.ts
src/app/game-state/home.service.ts

I found that these 3 follower types caused lag: farmer, hunter, scout.
I have fixed farmer and hunter.
Scout is fixed in #124 
At the same time i found a bug with field.yield.

Optimising followers

---

src/app/game-state/achievement.service.ts
src/app/game-state/home.service.ts

Fix: Homeslist adding Imperial homes twice

---

src/app/game-state/battle.service.ts

Don't let immortals get a free slap.

Fix: Immortal defeated combat health check

---

src/app/game-state/item-repo.service.ts
src/app/game-state/main-loop.service.ts
src/app/statistics-panel/statistics-panel.component.ts

Adds back in any banked ticks that went unused due to reaching frametime limiter in PR122

Offline tick readded

---

src/app/game-state/main-loop.service.ts

https://discord.com/channels/996414713766363146/999627950766956544/1004434235987349647

Fix for negative bankedTicks

---

src/app/attributes-panel/attributes-panel.component.html
src/app/game-state/activity.service.ts
src/app/game-state/battle.service.ts
src/app/game-state/character.service.ts
src/app/game-state/character.ts
src/app/game-state/hell.service.ts
src/app/game-state/home.service.ts
src/app/game-state/impossibleTask.service.ts
src/app/game-state/inventory.service.ts
src/app/game-state/main-loop.service.ts

- Removed deep copy of enemies via JSON as it was unnecessary. From what I can tell the reference is passed into the array and the garbage collection doesn't take it when the method returns due to the higher scope of the array, and thus does not impact gameplay.
- Moved description updaters to subscribers as they weren't necessary every tick.
- Moved Math to a frame subscriber to avoid excess tiny increment math calls from high tick counts.

Performance fixes

---

src/app/game-state/log.service.ts

Tore most of it out, works the same as before, just less looping and unshifts. Review to follow

Improve LogService performance

---

src/app/game-state/log.service.ts

https://discord.com/channels/996414713766363146/999627950766956544/1004695685100228620

Fixed memory leak in log.service

---

src/app/game-state/inventory.service.ts

This already happens for weapons

Armor format on create

---

src/app/follower-management-panel/follower-management-panel.component.html
src/app/game-state/activity.service.ts
src/app/home-panel/home-panel.component.ts
src/app/options-modal/options-modal.component.html

No reason to let the user input numbers smaller than zero.

Using the new totalPower for builder and added minimum to inputs

---

src/app/export-panel/export-panel.component.html
src/app/export-panel/export-panel.component.less
src/app/export-panel/export-panel.component.ts

https://discord.com/channels/996414713766363146/998578984730251276/1006513197483831296

File import and export

---

src/app/game-state/activity.service.ts

This should work.
I have tested with my live save and all my unlocked activities are shown.

If !activity.discovered then check meetsRequirements

---

src/app/app.component.ts
src/app/game-state/game-state.service.ts
src/app/game-state/inventory.service.ts
src/app/options-modal/options-modal.component.html
src/app/options-modal/options-modal.component.ts

Now updates after infusing equipment without autoequipbest enabled.

Fix: Not updating descriptions after Infusion

---

src/app/game-state/battle.service.ts

Damage done shown as negative

---

src/app/game-state/main-loop.service.ts

In case someone suspends on slow with banked checked I suppose.

Potential slow speed issue with banked

---

src/app/app.module.ts
src/app/game-state/main-loop.service.ts
src/app/offline-modal/offline-modal.component.html
src/app/offline-modal/offline-modal.component.less
src/app/offline-modal/offline-modal.component.spec.ts
src/app/offline-modal/offline-modal.component.ts

- Added very simple modal which can be expanded with more loading information
- fixed over-rewarding offline gains for inactive window
- some formatting.

Bugfix: Inactive gains + offline modal

---

src/app/attributes-panel/attributes-panel.component.html

Someone noticed a `<br/>` that shouldn't be there so i replaced it with a newline:
https://discord.com/channels/996414713766363146/999627950766956544/1010538761672740885

Follower tooltip removed <br/>

---

src/app/game-state/activity.service.ts

I am fairly sure there is supposed to be an if there.

Missing if for spiritActivity found

---

package-lock.json
src/app/game-state/achievement.service.ts
src/app/game-state/activity.service.ts
src/app/game-state/battle.service.ts
src/app/game-state/character.service.ts
src/app/game-state/character.ts
src/app/game-state/followers.service.ts
src/app/game-state/game-state.service.ts
src/app/game-state/hell.service.ts
src/app/game-state/home.service.ts
src/app/game-state/inventory.service.ts
src/app/game-state/item-repo.service.ts
src/app/game-state/log.service.ts
src/app/game-state/store.service.ts
src/app/log-filter-panel/log-filter-panel.component.html
src/app/log-filter-panel/log-filter-panel.component.ts
src/app/log-panel/log-panel.component.html
tsconfig.json

Refactored logging code to allow for easily adding or modifying log topics and put this logging more inline with existing libraries.
The last bit could just be my opinion though.

Logging refactor

---

.eslintrc.json
.prettierignore
.prettierrc.json
.vscode/extensions.json
.vscode/settings.json
package-lock.json
package.json

Results of these changes can be viewed by running `npx prettier --write .` from this branch.

Add Prettier

---

src/app/game-state/log.service.ts

Fixed issues with new game and unintentional changed save state.

logging fixes

---

src/app/game-state/item-repo.service.ts

Eating most produce is very similar, so the code can be extracted. Should support easier changes to produce stats in the future.

Extract eating produce into shared function

---

src/app/game-state/activity.service.ts
src/app/game-state/character.ts
src/app/game-state/followers.service.ts

Avoid a loop by using logarithms to calculate exact day training happens.
getProbUpgradeAfterDay = dailyFail^days
dailyFail = 1 - dailyUpgradeChance : math, static based on age, attribue, power
does not change over days
dailyFail^days = standard probability (static probability each day)
chance = dailyFail^days
log chance = days * log dailyFail
log chance / log dailyFail = days

TrainingSimplify

---

src/app/game-state/character.ts

Light optimization by hardcoding Math.log(100) in combat calc

hardcode Math.log(100)

---

src/app/common-buttons.service.spec.ts
src/app/common-buttons.service.ts
src/app/mobile-layout/mobile-activities/mobile-activities.component.html
src/app/mobile-layout/mobile-activities/mobile-activities.component.less
src/app/mobile-layout/mobile-drawer/mobile-drawer.component.html
src/app/mobile-layout/mobile-drawer/mobile-drawer.component.less
src/app/mobile-layout/mobile-drawer/mobile-drawer.component.spec.ts
src/app/mobile-layout/mobile-drawer/mobile-drawer.component.ts
src/app/mobile-layout/mobile-layout.component.html
src/app/mobile-layout/mobile-layout.component.less
src/app/mobile-layout/mobile-layout.component.ts
src/app/mobile-layout/mobile-time-buttons/mobile-time-buttons.component.html
src/app/mobile-layout/mobile-time-buttons/mobile-time-buttons.component.less
src/app/mobile-layout/mobile-time-buttons/mobile-time-buttons.component.spec.ts
src/app/mobile-layout/mobile-time-buttons/mobile-time-buttons.component.ts
src/app/mobile-layout/mobile-time/mobile-time.component.html
src/app/mobile-layout/mobile-time/mobile-time.component.less
src/app/mobile-layout/mobile-time/mobile-time.component.ts
src/app/standard-layout/standard-layout.component.html
src/app/standard-layout/standard-layout.component.ts

Add drawer
